name: aFastCrateReloaded
main: systems.amit.spigot.afastcratereloaded.Main
version: 1.1
author: amit177
depend: [CrateReloaded]
commands:
  afastcratereloaded:
    aliases: [afastcrates, fastcrates, afc]